using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityExtensionPatcher.Patches;

namespace BigPharmaExtensions.Patches
{
	class BigPharmaLoadExtensionManager : LineAdditionPatch
	{
		public override string InsertionPoint { get { return "// end of method Backbone::Awake"; } }
		public override Patch.PatchInsertionPosition InsertionPosition { get { return PatchInsertionPosition.After; } }
		public override int InsertionPointOffset { get { return 0; } }
		public override List<string> PatchLines
		{
			get
			{
				return new List<string>()
				{
".method public hidebysig ",
"	instance void LoadAssembly () cil managed ",
"{",
"	// Method begins at RVA 0x2248",
"	// Code size 196 (0xc4)",
"	.maxstack 4",
"	.locals init (",
"		[0] string modsFolder,",
"		[1] string assemblyFilePath,",
"		[2] string filePath,",
"		[3] class [mscorlib]System.Type t,",
"		[4] class [mscorlib]System.Reflection.MethodInfo initializeMethod,",
"		[5] bool CS$4$0000,",
"		[6] class [mscorlib]System.Type[] CS$6$0001,",
"		[7] int32 CS$7$0002",
"	)",
"",
"	IL_P_0000: nop",
"	IL_P_0001: ldstr \"Mods\"",
"	IL_P_0006: stloc.0",
"	IL_P_0007: ldstr \"BigPharmaExtensionAPI.dll\"",
"	IL_P_000c: stloc.1",
"	IL_P_000d: ldstr \"{0}/{1}/{2}\"",
"	IL_P_0012: call string ['Assembly-CSharp']Backbone::get_USER_DATA_PATH()",
"	IL_P_0017: ldloc.0",
"	IL_P_0018: ldloc.1",
"	IL_P_0019: call string [mscorlib]System.String::Format(string, object, object, object)",
"	IL_P_001e: stloc.2",
"	IL_P_001f: ldloc.2",
"	IL_P_0020: call bool [mscorlib]System.IO.File::Exists(string)",
"	IL_P_0025: ldc.i4.0",
"	IL_P_0026: ceq",
"	IL_P_0028: stloc.s CS$4$0000",
"	IL_P_002a: ldloc.s CS$4$0000",
"	IL_P_002c: brtrue IL_P_00c3",
"",
"	IL_P_0031: nop",
"	IL_P_0032: ldarg.0",
"	IL_P_0033: ldloc.2",
"	IL_P_0034: call class [mscorlib]System.Reflection.Assembly [mscorlib]System.Reflection.Assembly::LoadFrom(string)",
"	IL_P_0039: stfld class [mscorlib]System.Reflection.Assembly Backbone::extensionManagerAssembly",
"	IL_P_003e: ldarg.0",
"	IL_P_003f: ldarg.0",
"	IL_P_0040: ldfld class [mscorlib]System.Reflection.Assembly Backbone::extensionManagerAssembly",
"	IL_P_0045: callvirt instance class [mscorlib]System.Type[] [mscorlib]System.Reflection.Assembly::GetTypes()",
"	IL_P_004a: stfld class [mscorlib]System.Type[] Backbone::extensionManagerTypes",
"	IL_P_004f: nop",
"	IL_P_0050: ldarg.0",
"	IL_P_0051: ldfld class [mscorlib]System.Type[] Backbone::extensionManagerTypes",
"	IL_P_0056: stloc.s CS$6$0001",
"	IL_P_0058: ldc.i4.0",
"	IL_P_0059: stloc.s CS$7$0002",
"	IL_P_005b: br.s IL_P_00b4",
"	// loop start (head: IL_P_00b4)",
"		IL_P_005d: ldloc.s CS$6$0001",
"		IL_P_005f: ldloc.s CS$7$0002",
"		IL_P_0061: ldelem.ref",
"		IL_P_0062: stloc.3",
"		IL_P_0063: nop",
"		IL_P_0064: ldloc.3",
"		IL_P_0065: callvirt instance string [mscorlib]System.Type::get_FullName()",
"		IL_P_006a: ldstr \"BigPharmaExtensionAPI.ExtensionManager\"",
"		IL_P_006f: callvirt instance bool [mscorlib]System.String::Equals(string)",
"		IL_P_0074: ldc.i4.0",
"		IL_P_0075: ceq",
"		IL_P_0077: stloc.s CS$4$0000",
"		IL_P_0079: ldloc.s CS$4$0000",
"		IL_P_007b: brtrue.s IL_P_00ad",
"",
"		IL_P_007d: nop",
"		IL_P_007e: ldarg.0",
"		IL_P_007f: ldloc.3",
"		IL_P_0080: ldc.i4.1",
"		IL_P_0081: call object [mscorlib]System.Activator::CreateInstance(class [mscorlib]System.Type, bool)",
"		IL_P_0086: stfld object Backbone::extensionManagerObject",
"		IL_P_008b: ldloc.3",
"		IL_P_008c: ldstr \"Initialize\"",
"		IL_P_0091: callvirt instance class [mscorlib]System.Reflection.MethodInfo [mscorlib]System.Type::GetMethod(string)",
"		IL_P_0096: stloc.s initializeMethod",
"		IL_P_0098: ldloc.s initializeMethod",
"		IL_P_009a: ldarg.0",
"		IL_P_009b: ldfld object Backbone::extensionManagerObject",
"		IL_P_00a0: ldc.i4.0",
"		IL_P_00a1: newarr [mscorlib]System.Object",
"		IL_P_00a6: callvirt instance object [mscorlib]System.Reflection.MethodBase::Invoke(object, object[])",
"		IL_P_00ab: pop",
"		IL_P_00ac: nop",
"",
"		IL_P_00ad: nop",
"		IL_P_00ae: ldloc.s CS$7$0002",
"		IL_P_00b0: ldc.i4.1",
"		IL_P_00b1: add",
"		IL_P_00b2: stloc.s CS$7$0002",
"",
"		IL_P_00b4: ldloc.s CS$7$0002",
"		IL_P_00b6: ldloc.s CS$6$0001",
"		IL_P_00b8: ldlen",
"		IL_P_00b9: conv.i4",
"		IL_P_00ba: clt",
"		IL_P_00bc: stloc.s CS$4$0000",
"		IL_P_00be: ldloc.s CS$4$0000",
"		IL_P_00c0: brtrue.s IL_P_005d",
"	// end loop",
"",
"	IL_P_00c2: nop",
"",
"	IL_P_00c3: ret",
"} // end of method ExtensionManager::LoadAssembly",
"",
				};
			}
		}

	}
}
